#import "../fragments/ImageFragment.gql"
#import "../fragments/ScenePerformerFragment.gql"
#import "../fragments/URLFragment.gql"
fragment SceneFragment on Scene {
  id
  release_date
  production_date
  title
  deleted
  details
  director
  code
  duration
  urls {
    ...URLFragment
  }
  images {
    ...ImageFragment
  }
  studio {
    id
    name
    parent {
      id
      name
    }
  }
  performers {
    as
    performer {
      ...ScenePerformerFragment
    }
  }
  fingerprints {
    id
    hash
    algorithm
    duration
    part
    submissions
    reports
    user_part_set
    user_submitted
    user_reported
    created
    updated
  }
  tags {
    id
    name
    description
    aliases
  }
}
